accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup' , views.signup_view , name="signup" ),
    path('login', views.login_view , name="login"),
    path('logout',views.logout_view , name = "logout"),
]

articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'
urlpatterns = [
    path('' , views.articles_list , name = "list"),
    path('create', views.create_article , name="create"),
    path("<slug>" , views.articles_detail , name = 'detail') , 
]

djBlog/urls.py
from django.contrib import admin
from django.urls import path , include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('' , views.home),
    path('about/', views.about),
    path('articles/' , include('articles.urls')),
    path('accounts/' , include('accounts.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL , document_root = settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

articles/models.py
from django.db import models
from django.contrib.auth.models import User

class Articles(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField()
    body = models.TextField()
    date = models.DateField(auto_now_add = True)
    image = models.ImageField(default='default.jpg' , blank=True)
    author = models.ForeignKey(User,default=None,on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    def shortBody(self):
        return self.body[:50] + " ..."

articles/forms.py
from django import forms
from . import models

class CreateArticle(forms.ModelForm):
    class Meta:
        model = models.Articles
        fields = ['title','slug','body','image']

accounts/views.py
from django.shortcuts import render , redirect
from django.contrib.auth.forms import UserCreationForm , AuthenticationForm
from django.contrib.auth import login,logout

def signup_view (request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request,user)
            return redirect('articles:list')
    else:
        form = UserCreationForm()
    
    return render(request , 'accounts/signup.html' , {'form' : form})

def login_view(request):
    if request.method == "POST":
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request,user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect("articles:list")
    else:
        form = AuthenticationForm()
    return render(request,'accounts/login.html' , {'form':form})

def logout_view(request):
    if request.method == "POST":
        logout(request)
        return redirect("articles:list")

articles/views.py
from django.shortcuts import render,redirect
from . import models
from django.contrib.auth.decorators import login_required
from . import forms

def articles_list(request):
    articles = models.Articles.objects.all().order_by('date')
    return render(request , 'articles/articleslist.html' , {'articles': articles})

def articles_detail(request , slug):
    articles = models.Articles.objects.get(slug=slug)
    return render(request , 'articles/articledetail.html' , {'articles': articles})

@login_required(login_url="/accounts/login")
def create_article(request):
    if request.method == "POST":
        form = forms.CreateArticle(request.POST,request.FILES)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.author = request.user
            instance.save()
            return redirect('articles:list')
    else:
        form = forms.CreateArticle()

    return render(request , 'articles/createarticle.html' , {'form':form})

djBlog/views.py
from django.shortcuts import render
from django.shortcuts import HttpResponse

def home(requst):
    return render(requst , "Home.html")

def about(requst):
    return render(requst , "About.html")

accounts/templates/accounts/login.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>signup</title>
</head>
<body>
    <form method="post" action="/accounts/login">
        {{form}}
        {% csrf_token %}
        {% if request.GET.next %}
        <input type="hidden" name="next" value="{{request.GET.next}}">
        {% endif %}
        <input type="submit" value="login" >
    </form>
</body>
</html>

accounts/templates/accounts/signup.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>login</title>
</head>
<body>
    <form method="post" action="/accounts/signup">
        {{form}}
        {% csrf_token %}
        <input type="submit" value="signup" >
    </form>
</body>
</html>

articles/templates/articles/articledetail.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
    <h1>{{articles.title}}</h1>
    <p>{{articles.body}}</p>
    <img src="{{articles.image.url}}" alt="">
    <p style="color: blue ;">{{articles.date}}</p>
</body>
</html>

articles/templates/articles/articlesName.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>
        this is page that show articles writer
    </h1>
</body>
</html>

articles/templates/articles/articleslist.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'styles.css' %}">
    <title>Article page</Article></title>
</head>
<body>
    <h1 style="background-color: red;">Article page</h1>
    {% for art in articles %} 
    <h1><a href="{% url 'articles:detail' slug=art.slug %}">{{art.title}}</a></h1>
    <p>{{art.shortBody}}</p>
    <p>{{art.date}}</p>
    <p>{{art.author}}</p>
    {% endfor %}
    <form action="{% url 'accounts:logout' %}" method="post">
        {% csrf_token %}
        <button type="submit">logout</button>
    </form>
    
</body>
</html>

articles/templates/articles/createarticle.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <p>create your article</p>
    <form action="{% url 'articles:create' %}" method="post" enctype="multipart/form-data">
        {{form}}
        {% csrf_token %}
        <input type="submit" value="create">
    </form>
</body>
</html>

templates/About.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>About page</h1>
    <form>
        name: <input type="text">
    </form>
</body>
</html>

templates/Home.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>خانه</title>
</head>
<body>
    <h1>Home page</h1>
</body>
</html>